interface DailyHints {
  [key: string]: string;
}

const dailyHints: DailyHints = {
  "2024-08-04": "Here is a haiku hint for the recipe:\n\nDarkness gathered slow\nFires fueled by ancient hearts beat\nEarthly secrets hide",
  "2024-08-05": "Golden core within\nThree times, rugged iron forms\nMighty block arises",
  "2024-08-06": "Here's a haiku hint for the recipe:\n\nRich earth yields its wealth\nThree times, in harmony sweet\nCopper's secret birth",
  "2024-08-07": "Golden dreams unfold\nRays of sunshine shape the air\nValue in small form",
  "2024-08-09": "Forged in fiery depths\nAncient secrets whispered loud\nSolidity's grasp",
  "2024-08-10": "Ancient secrets tell\nThree times three, a treasure's birth\nRusty paths unfold",
  "2024-08-11": "Golden treasure sought\nIn the darkness, shine it bright\nThreefold richness found",
  "2024-08-12": "Ancient secrets sleep\nTreasured fragments intertwined\nRare and precious keep",
  "2024-08-13": "In fiery depths below\nGolden threads of strength entwined\nNether's secret kept",
  "2024-08-18": "Rich, warm metal flows\nCascading steps of golden\nNature's harmony",
  "2024-08-19": "Copper's gentle slope\nMidnight whispers secrets\nStairway to the sky",
  "2024-08-20": "Ancient paths unwind\nCopper's worn and weathered face\nStairs to secrets hide",
  "2024-08-21": "Ancient secrets sleep\nRusty hues in repetition\nGolden steps rise",
  "2024-09-03": "Golden threads unwind\nRoughened edges meet in flight\nStairs of smooth design",
  "2024-09-04": "Copper's gentle glow\nTwisted threads of waxed design\nSteps in secret rise",
  "2024-09-05": "Whispers of the past\nCopper's gentle, worn shape\nStairs to secrets lie",
  "2024-09-06": "Here is a haiku hint for the recipe:\n\nAncient secrets rise\nIn steps of worn, weathered pride\nCrafting's gentle",
  "2024-09-30": "Purple's subtle sway\nAmidst transparent, gentle\nBeauty's hazy form",
  "2024-10-01": "Moonlit depths within\nAncient secrets whispered\nThreefold harmony",
  "2024-11-17": "Wooden words entwined\nPages turned in silent hush\nWisdom's wooden throne",
  "2024-11-23": "Ancient secrets rise\nMystic threads weave stairway\nPurpur's noble path",
  "2024-11-24": "Wooden walls surround\nNature's strength in humble form\nSecrets locked inside",
  "2024-11-26": "Whispers of warmth rise\nCrumbling walls hold secret key\nAncient hearts abide",
  "2024-11-27": "Wooden whispers rise\nStick by stick, a path unwinds\nClimb to hidden skies",
  "2024-11-28": "Ancient stone whispers\nThree times folded, stairs arise\nRocky pathways call",
  "2024-12-02": "Whispers of the past\nAncient secrets in the wood\nMusic echoes fast",
  "2024-12-14": "Ancient darkness falls\nTorch of fiery, glowing soul\nIn the void's sweet call",
  "2024-12-25": "Forged in gentle fire\nTwisted threads of strength entwined\nHeavy, cold desire",
  "2024-12-27": "Golden sunset's gift\nSummer's sweet and juicy song\nGrowing in delight",
  "2024-12-28": "Mighty builder's quest\nThree times the solid foundation\nSteps to higher rest",
  "2024-12-29": "Building's sturdy base\nRocky foundation takes shape\nSteps unfold with ease",
  "2024-12-30": "Building blocks of earth arise\nMuddy foundations take shape slow\nClimb to new heights now",
  "2025-01-03": "Flickering darkness falls\nMasonry's ancient whispers\nStairway to the deep",
  "2025-01-04": "Mystic arts unfold\nMidnight stones and ancient tome\nWisdom's secret kept",
  "2025-01-06": "Golden light descends\nLayers of earthy calm rise\nStairway to the sky",
  "2025-01-07": "Darkness holds the key\nAncient power in its grasp\nMystery unfolds",
  "2025-01-08": "Here is a haiku hint for the recipe:\n\nGlowing green depths sleep\nRare and precious, yet so bright\nNature's treasure keep",
  "2025-01-09": "Ancient wood whispers\nClimbing vines hold secrets tight\nStairway to the sky",
  "2025-01-10": "Softly wooden sound\nRhythmic patterns all around\nWisdom's humble form",
  "2025-01-11": "Here is a haiku hint for the Minecraft recipe:\n\nWooden steps unfold\nNature's rhythm, gentle rise\nBuild on solid ground",
  "2025-01-12": "Softly woven night\nTreetop whispers, secret stairs\nJungle's hidden path",
  "2025-01-13": "Silky threads entwined\nGolden light on ancient wood\nSteps for distant hills",
  "2025-01-14": "Here is a haiku hint for the recipe:\n\nWooden paths unwind\nTwists and turns in secret ways\nSteps to hidden deep",
  "2025-01-15": "Tall and twisted trees\nWooden steps in secret deep\nMystery ascends",
  "2025-01-16": "Rusty hues unfold\nTwisted threads of crimson bind\nSecrets in the dark",
  "2025-01-17": "Fibers twist and turn\nMystic paths unfold below\nStep into the haze",
  "2025-01-18": "Moonlit towers rise\nDarkness yields to guiding light\nMystery abides",
  "2025-02-10": "Forging a path keen\nGather strength in threefold row\nIron's heavy test",
  "2025-02-15": "Sparkling blocks align\nCrystalline peaks touch the sky\nFragile beauty stands",
  "2025-02-16": "Softly glowing hue\nEarth's warmth mixed with color's breath\nTerracotta's new",
  "2025-02-17": "Vibrant hue unfurls\nEarthy tones entwined with charm\nSummer's warmth revealed",
  "2025-02-18": "Softly glowing block\nFaded hue on crimson base\nTerracotta's charm",
  "2025-02-19": "Earthly mix unfolds\nColor's gentle, subtle hue\nSoftly glows within",
  "2025-02-20": "Golden hues unfold\nEarthy tones in harmony\nSunset's gentle glow",
  "2025-02-21": "Earthy hues combine\nLime's vibrant zing takes its place\nRustic charm entwines",
  "2025-02-22": "Earthly hue desired\nDust of pink upon the ground\nTerra's gentle dance",
  "2025-02-23": "Earthly hues abide\nAncient charm within is spun\nGrayness slowly dyes",
  "2025-02-24": "Earthly hues unfold\nSoftly dyed, three-fold design\nGrayness takes its toll",
  "2025-02-25": "Ancient earthy tone\nMix with secret's gentle hue\nTerra's subtle blend",
  "2025-02-26": "Fired earth's gentle hue\nRoses tint the familiar\nMolded, yet anew",
  "2025-02-27": "Earthy hues unfold\nRays of color gently play\nMidnight's subtle glow",
  "2025-02-28": "Earthly hues unfold\nMuddy tone in ancient form\nNature's rustic gold",
  "2025-03-01": "Earthy tones unfold\nGarden's gentle hue takes hold\nNature's subtle charm",
  "2025-03-02": "Earth's gentle hue sought\nFired clay meets dye's subtle touch\nVibrant red is born",
  "2025-03-03": "Earthy tones prevail\nMolded by the artisan's hand\nMidnight's subtle hue",
  "2025-03-04": "Golden fields of old\nSun-kissed stalks in triple fold\nBundled, soft and told",
  "2025-03-22": "Mortal's subtle quest\nGlassy hues of purity\nWhispers in the light",
  "2025-03-23": "Here is a haiku hint for the recipe:\n\nTransparent threads weave\nOrange hue in secret mix\nGlassy, vibrant glow",
  "2025-03-24": "Golden light descends\nRuby hue upon the pane\nMystery within",
  "2025-03-25": "Faded summer sky\nDusty hues of calm descent\nGlassy truth revealed",
  "2025-03-26": "Sun-kissed hues unfold\nGlinting tears of liquid gold\nMelding, colors cold",
  "2025-03-27": "Golden hue, pure and bright\nMidday warmth on dusty day\nColorful delight",
  "2025-03-28": "Golden light does flow\nPigment of passion within\nGlassy beauty grows",
  "2025-03-29": "Moonlit veil unfurls\nMidnight hues on silent seas\nGrayness in the air",
  "2025-03-30": "Golden hues entwined\nMidnight calm in swirling dance\nGrayness takes its form",
  "2025-03-31": "Whispers of the blue\nGlassy threads weave secrets tight\nMidnight's subtle hue",
  "2025-04-01": "Shimmering purple dreams\nMidnight whispers, hidden hue\nGlassy secrets keep",
  "2025-04-02": "Golden light does play\nMidnight hues in secret blend\nGlassy secrets made",
  "2025-04-03": "Sunset's gentle hue\nGolden threads of darkness weave\nBrownness slowly gleams",
  "2025-04-04": "Golden light descends slow\nMidnight hue in secret mix\nEmerald's glow shows",
  "2025-04-05": "Golden hues arise\nMystery's subtle design\nFlecks of passion's fire",
  "2025-04-06": "Midnight's secret art\nShadows dance upon the pane\nGlassy darkness born",
  "2025-04-24": "Golden hues descend\nOcean's secrets slowly form\nMystery within",
  "2025-04-25": "Dark depths yield to might\nShards of ancient blue collide\nOcean's midnight song",
  "2025-04-26": "Golden blocks ascend\nOcean's essence, stair by stair\nBuilding on the",
  "2025-04-27": "Ancient ocean's might\nBrick by brick, stairs take shape slow\nDepth in every step",
  "2025-04-28": "Ocean's secret kept deep\nGlinting darkness, steps ascend\nMidnight's mystic sleep",
  "2025-04-29": "Glimmering depths below\nOcean's secrets whispered loud\nMoonlit path to know",
  "2025-05-03": "Ancient desert's hue\nSandstone secrets hidden deep\nLayered steps arise",
  "2025-05-05": "Mystic fungi's might\nTwisted growth in darkest depths\nWarty secrets keep",
  "2025-05-07": "Whispers of the past\nAshen remnants take form slow\nFleshless artistry",
  "2025-05-08": "Whispers in the dark\nSilent guardians entwine\nSecrets unfold slow",
  "2025-05-25": "Frosty secrets sleep\nTriple layer of silence\nWinter's icy sigh",
  "2025-05-26": "Sea's dark depths whisper low\nTreasures hidden, hearts do glow\nMystery unfolds slow",
  "2025-05-27": "Granite's gentle form\nSteps unfold, like morning dew\nRocky path is found",
  "2025-05-28": "Ancient structures rise\nRusty red whispers secrets\nFamiliar foundation",
  "2025-05-29": "Here is a haiku hint for the recipe:\n\nAncient stones align\nNature's secrets whispered sweet\nSteps to mystic land",
  "2025-05-30": "Ancient stones align\nRough edges smoothed by time's hand\nStepwise wisdom born",
  "2025-05-31": "Ancient walls arise\nMossy secrets unfold slow\nNature's stairway",
  "2025-06-01": "Ancient stone whispers\nTriple layer of descent\nLadders to the past",
  "2025-06-02": "Ancient paths unfold\nLayered secrets take shape slow\nSturdy steps abide",
  "2025-06-03": "Softly falling sands\nGentle slope to climb again\nSlumbering giants",
  "2025-06-04": "Whispers of the deep\nQuartz whispers echo upwards\nMystic steps unfold",
  "2025-06-05": "Rocky path unwinds\nThreefold harmony sought high\nAncient steps revealed",
  "2025-06-06": "Stone by stone we rise\nAncient secrets in the air\nMystic paths unfold",
  "2025-06-07": "Ancient flames ascend\nMoldering earth yields its might\nRuddy secrets kept",
  "2025-06-08": "Stone whispers secrets low\nAncient wisdom in the air\nSteps unfold below",
  "2025-06-09": "Rocky foundation sought\nTwice the strength in every step\nSolidity is key",
  "2025-06-10": "Ancient stones rise high\nEarth's secrets whispered slow\nPathways to the sky",
  "2025-06-11": "Slumbering earth yields\nSteps that shine like morning dew\nMidnight's gentle slope",
  "2025-06-12": "Rough, dark foundation\nAncient secrets lie within\nSteps to new depths rise",
  "2025-06-13": "Terra's ancient form\nBlocks of darkness stacked high rise\nMystery unfurls",
  "2025-07-01": "Whispered ancient tale\nFibers weave a fragile form\nStructures start to rise",
  "2025-07-04": "Ancient secrets sleep\nResistive whispers unfold\nMystery's spark keeps",
  "2025-07-06": "Ancient wisdom's spark\nTorchlight guides the quiet heart\nTruth in secret kept",
  "2025-07-07": "Ancient contraption\nMystic woods entwined with fire\nPower's gentle grasp",
  "2025-07-09": "Golden goo does flow\nSlick and slow, yet firm as stone\nSlithy secret kept",
  "2025-07-11": "Ancient secrets keep\nStony whispers in the dark\nMystery unsealed",
  "2025-07-12": "Mining deep within\nIron's secrets slowly yield\nCrimson treasures rise",
  "2025-07-13": "Ancient crafts reveal\nMystic threads weave hidden fate\nTrigger's quiet sleep",
  "2025-07-14": "Whispers in the dark\nMystic stones align with power\nSecrets slowly fall",
  "2025-07-15": "Ancient tales unfold\nGolden pages hold the key\nWisdom's silent",
  "2025-07-16": "Ancient secrets hidden\nRuby pulses, whispers low\nGuided by the keen",
  "2025-07-18": "Conductive curves dance\nMalleable forces align\nElectric whispers",
  "2025-07-19": "Golden light descends\nSlumbering wood awakens\nDay's gentle whisper",
  "2025-07-20": "Wooden whispers wait\nIron threads entwined in fate\nSnap, and all is set",
  "2025-07-22": "Explosive secrets shared\nGolden dust and sandy base\nDanger's hidden heart",
  "2025-07-23": "Here is a haiku hint for the recipe:\n\nDarkness lit by spark\nTwice-burned fuel that shines so bright\nLamp's warm, guiding mark",
  "2025-07-24": "Wooden whispers rise\nEchoing the silent beat\nOak's rhythmic surprise",
  "2025-08-18": "Fortress walls await\nStrong and sturdy, yet so fine\nIron's steady beat",
  "2025-08-19": "Whispers of wood's song\nSturdy frame takes shape slow\nNature's gentle gate",
  "2025-08-20": "Whispers of the wood\nForest's gentle, ancient heart\nCrafted silence keeps",
  "2025-08-21": "Wooden whispers rise\nNature's symmetry sought\nCrafty secrets keep",
  "2025-08-22": "Whispers of the deep\nAncient secrets in the night\nForest's gentle keep",
  "2025-08-23": "Golden light fades low\nThree times sturdy, once a crown\nNature's door ajar",
  "2025-08-24": "Ancient tree's dark heart\nWooden slats in solemn row\nCrafting's secret",
  "2025-08-25": "Whispers of the deep\nPlank by plank, a secret\nDoorways softly sleep",
  "2025-08-26": "Blood-hued boards abound\nMystery's crimson veil falls\nGates to secrets found",
  "2025-08-27": "Whispers of the deep\nTwisted woods in secret keep\nMystic doors unfold",
  "2025-09-16": "Golden paths unfold\nMystic force within its core\nPower flows, hearts told",
  "2025-09-17": "Rail of insight sought\nIron's path, plate's gentle touch\nRedstone's heartbeat beats",
  "2025-09-18": "Iron's rhythmic sway\nStick in harmony with might\nRailway's gentle way",
  "2025-09-19": "Railway whispers low\nIron threads of power spun high\nTorchlit secrets flow",
  "2025-10-13": "Silky threads entwined\nSturdy frames hold gentle power\nNature's harmony",
  "2025-10-14": "Ancient artistry\nWhispers of flying silence\nDeadly gentle song",
  "2025-10-26": "Softly yields its strength\nGentle touch forges a blade\nNature's silent clue",
  "2025-10-27": "Moonlit forest floor\nGentle grasp of twigs entwined\nDigging with care now",
  "2025-10-28": "Gentle earthy form\nTwigs entwined, wooden heart beats\nCrafting's quiet",
  "2025-10-29": "Whispered forest deep\nAncient secrets in the air\nTool of humble keep",
  "2025-10-30": "Silent forest heart\nTwigs that weave a gentle art\nNature's tender start",
  "2025-10-31": "Ancient earthy heart\nForged in fire's gentle grasp\nSharpness slowly born",
  "2025-11-01": "Ancient earthy form\nTwinned sticks of gentle touch sought\nForged in humble home",
  "2025-11-02": "Ancient tools arise\nHarvest's gentle, steady beat\nEarth yields to our might",
  "2025-11-03": "Ancient tools arise\nRough edges shape the future\nHarvest's gentle",
  "2025-11-04": "Ancient earthy charm\nForged in darkness, gentle\nHarvest's subtle form",
  "2025-11-05": "Ancient secrets yield\nGolden light on whittled wood\nWisdom's sharp guide",
  "2025-11-06": "Whispers of the sun\nAncient wisdom in the dark\nDig with gentle touch",
  "2025-11-07": "Ancient secrets yield\nGolden tool of gentle touch\nMidday's fiery gleam",
  "2025-11-08": "Golden glow within\nAncient tool's new, sharp design\nStrength in humble form",
  "2025-11-09": "Golden light descends\nTwisted sticks, pure hearts entwined\nTilling the earth's end",
  "2025-11-10": "Glowing darkness yields\nFierce edge from ancient heartwood\nWisdom's keenest point",
  "2025-11-11": "Digging deep, I find\nTools of earth and air entwined\nCrafting's gentle",
  "2025-11-12": "Metal's sturdy form\nStick-like shape, strength in its heart\nDigging's gentle norm",
  "2025-11-13": "Ancient secrets yield\nForged in fire's gentle grasp\nTool of iron dreams",
  "2025-11-14": "Fertile ground awaits\nGolden light upon the dark\nTill the earth with ease",
  "2025-11-15": "Rare gemstones align\nTool of old, sharp as a mind\nCutting through the din",
  "2025-11-16": "A gem to dig with care\nStick by stick, a secret's shared\nBuried truth to spare",
  "2025-11-17": "Shining tools await\nGolden threads entwined with might\nTreasures dig deep",
  "2025-11-18": "Moonlit edge awaits\nGentle touch on ancient wood\nSharpness in the night",
  "2025-11-19": "Golden light abides\nFragile strength in gentle grasp\nHarvest's silent",
  "2025-11-26": "Softly worn by few\nWrapped in protection's fold\nCrafted, not for none",
  "2025-11-27": "Softly worn by night\nGentle curves, no sharp delight\nWrap yourself in time",
  "2025-11-30": "Iron's sturdy form takes\nTriple layer of strength forms\nChestplate, armor's core",
  "2025-12-01": "Forged in iron's heart\nThreefold strength in legging form\nProtected from start",
  "2025-12-04": "Golden paths unfold\nTwice-told tale of precious\nThreefold strength held deep",
  "2025-12-05": "Shining armor bright\nThreefold bond of precious stone\nLegs adorned with might",
  "2025-12-08": "Golden armor's might\nTreasures hidden, warmth takes flight\nMidnight's gentle",
  "2025-12-09": "Golden threads entwined bright\nMidnight darkness holds the key\nLegs of shining light",
  "2025-12-11": "Whispers of the past\nGolden threads upon brown\nSecrets slowly form",
  "2025-12-12": "Golden glow descends\nMidnight sweetness in its fold\nSunset's secret keeps",
  "2025-12-13": "Wooden words entwined tight\nNature's whisper, simple form\nMarking paths at night",
  "2025-12-14": "Crafty fingers weave fate\nNature's secrets whispered free\nTree-like wisdom waits",
  "2025-12-15": "Whispers of the wood\nSticky note in silent\nNature's gentle",
  "2025-12-16": "Vines entwined with care\nNature's whispers on the wall\nMystery revealed",
  "2025-12-17": "Whispered ancient tales\nMysterious woods unfold\nSignpost secrets kept",
  "2025-12-18": "Ancient woods whisper\nMystery held by the stalk\nSignposts mark the way",
  "2025-12-19": "Wooden whispers rise\nTropical forests unfold\nNature's secret sign",
  "2025-12-20": "Ancient walls of red\nMystic marks in wooden grasp\nSecrets are revealed",
  "2025-12-21": "Mysterious signs arise\nTwisted wood and ancient charm\nMarking secret paths",
  "2025-12-24": "Ancient secrets bloom\nSeaweed's wispy threads entwine\nNature's gift unfurls",
  "2025-12-28": "Here is a haiku hint for the Compass recipe:\n\nFamiliar paths worn\nIron's guiding force revealed\nNorthward steps unfold",
  "2025-12-29": "Whispers in the dark\nThree of a kind, one outlier\nGuidance is key",
  "2025-12-30": "Whispers of the deep\nStick and silken threads entwined\nFishing's gentle sleep",
  "2025-12-31": "Whirring time's passage\nGolden threads of rhythm weave\nMidnight's silent mark",
  "2026-01-01": "Mystic desert seeks\nGolden views in dark night's grasp\nShadows yield to me",
  "2026-01-19": "Whispered farm delight\nGolden drips on tender bed\nSummer's sweet surprise",
  "2026-02-16": "Ancient craft unfolds\nForged in iron's fiery core\nThree times, strong as one",
  "2026-02-18": "Golden light descends\nMelon's juicy secret shared\nMidnight's warm friend given",
  "2026-02-21": "Framing the unknown\nStick-like whispers surround it\nLeather's gentle hold",
  "2026-02-24": "Whispers of the road\nParchment paths and winding ways\nCartographer's tale",
  "2026-02-25": "Golden hues abound\nThree times, a treasure yields sweet\nShining prize is found",
  "2026-03-01": "Crafty hands hold strong\nThree pillars stand tall alone\nStone support beneath",
  "2026-03-02": "Softly wraps the steed\nTriple layers of gentle\nProtection's shield",
  "2026-03-03": "Here is a haiku hint for the recipe:\n\nIn dark depths I find\nSlippery surprise within\nLeaden path unfolds",
  "2026-03-04": "Fuzzy, gentle hue\nTwisted thread in silent form\nPure, simple design",
  "2026-03-05": "Softly glowing stack\nTwisted threads weave vibrant form\nSunset's gentle hue",
  "2026-03-06": "Softly glowing threads\nTwist and turn in secret dance\nMidnight's crimson",
  "2026-03-07": "Faded morning dew\nThree times softness wraps the air\nWooden frame awaits",
  "2026-03-08": "Softly glowing threads\nWarmth and sunshine in the air\nYellow's gentle hush",
  "2026-03-09": "Golden threads entwined tight\nLime's vibrant hue takes flight\nNature's subtle might",
  "2026-03-10": "Softly glowing threads\nThreefold whispers of the heart\nStick amidst the haze",
  "2026-03-11": "Softly wraps the truth\nMidnight hue, yet gentle soul\nWisdom's quiet mark",
  "2026-03-12": "Softly shining bright\nWoolly wraps in simple fold\nThree times a truth keeps",
  "2026-03-13": "Softly glowing threads\nWoven in harmony sweet\nNature's gentle hue",
  "2026-03-14": "Softly woven shade\nTwice-fold symmetry revealed\nNature's gentle hue",
  "2026-03-15": "Softly woven threads\nTwist and turn, in gentle hue\nMystic symbols rise",
  "2026-03-16": "Softly woven might\nGolden threads entwined in dark\nBrown elegance",
  "2026-03-17": "Crafting's verdant dream\nWoven threads of nature's hue\nStick stirs in the midst",
  "2026-03-18": "Softly glowing deep\nThreefold symmetry sought\nWarmth in morning keep",
  "2026-03-19": "Silent darkness falls\nWoolen whispers weave the air\nStick of solitude",
  "2026-03-20": "Moonlit whispers rise\nGlimmering tears meet the sea\nCrystalized surprise",
  "2026-03-22": "Moonlit threads align\nGlowing sparks in darkness spin\nMystery takes flight",
  "2026-03-23": "Ancient forest's might\nWooden pillars stand strong guard\nProtection takes flight",
  "2026-03-25": "Harmony's gentle song\nFragments of sound align sweet\nSymphony takes",
  "2026-03-26": "Crafty hands weave fate\nThree prongs of ancient lore rise\nDeadly aim awaits",
  "2026-04-01": "Golden days arise\nNature's cycle is key here\nWooden wisdom flows",
  "2026-04-02": "Wooden vessel takes shape\nNature's curves in harmony\nSturdy, yet so frail",
  "2026-04-03": "Ancient logs entwined\nSmokey secrets slowly born\nWooden whispers rise",
  "2026-04-04": "Iron's fiery nest\nThree smooth stones, iron's strong hold\nFurnace's secret",
  "2026-04-05": "Maps unfold with care\nWooden frame and pages blend\nKnowledge's subtle snare",
  "2026-04-06": "Whispered woods arise\nGentle sparks upon the floor\nCrafty fingers weave",
  "2026-04-08": "Ancient craft unfurls\nIron beats upon wood's heart\nStrength in simple forms",
  "2026-04-10": "Moonlit path ahead\nGolden glow in iron form\nLighting the way",
  "2026-04-11": "Flickering, faint glow\nForged in darkness, iron heart\nLantern's secret",
  "2026-04-12": "Flickering delight\nTangled threads of ancient wood\nWarmth in darkest night",
  "2026-04-13": "Flames that dance at night\nTwigs and whispers of the deep\nAncient secrets lit",
  "2026-04-14": "Golden secrets within\nWooden walls hold sweet surprise\nSummer's gentle spin",
  "2026-04-17": "Ancient stones align\nEarth's power in secret form\nMystic force is born",
  "2026-04-19": "A secret staircase lies hidden deep\nIn darkness, shadows take shape\nThree of a kind asleep",
  "2026-04-22": "Ancient stones aligned\nMidnight beauty takes shape slow\nDarkness yields to rise",
  "2026-04-26": "Golden paths unwind\nDarkness yields to radiant\nSteps to secret depths",
  "2026-04-27": "Moonlit tears fall slow\nGlowing whispers in the dark\nSoul's gentle anchor"
};

export default dailyHints;
